### ISSUE TITLE
Invalid JSON

### ISSUE THREAD

**Issue by 89z** [zerodytrash/YouTube-Internal-Clients#2]
This is not valid JSON:

<https://github.com/zerodytrash/YouTube-Internal-Clients/blob/727394456be7c4ba3f76d37b64dc81ed688816e1/payloads/post_data.txt#L9-L11>

it seems that maybe the server accepts it regardless, but given the nature of this project, I wouldnt want to give the server any excuse to reject a request.

**Comment by 89z** [comment]
Also, its in the wrong place. Should look like this:

~~~
{
  "context": {
    "client": {
      "clientName": "TVHTML5_SIMPLY_EMBEDDED_PLAYER",
      "clientVersion": "2.0"
    },
    "thirdParty": {
      "embedUrl": "https://www.youtube.com/"
    }
  },
  "videoId": "HsUATh_Nc2U"
}
~~~

**Comment by zerodytrash** [comment]
Oh, good catch! Will fix that asap and run it again. maybe this changes something in the results.

**Comment by 89z** [comment]
I think it depends on the video. For example, for video `HsUATh_Nc2U`, you must use `thirdParty`, and it must be in correction location, otherwise `streamingData` will be empty.

**Comment by 89z** [comment]
If it helps, I have a pretty decent set of tests here:

https://github.com/89z/mech/blob/v1.51.3/youtube/client_test.go

I pulled it from the YT-DLP repo. I have been trying to decide what to do about the throttling, I think I have an idea about another approach.

**Comment by zerodytrash** [comment]
i just tested the latest version of yt-dlp. the video `dqRZDebPIGs` (18.8MB) is downloaded in only two seconds using the tvhtml5 embedded client. But now I see that it is only the 360p version that has a `ratebypass=yes` parameter (is that what you need to avoid throttling?). When i download the 1080p version (68.5MB) then i takes 8 seconds for the 5 minute video.

**Comment by 89z** [comment]
> i just tested the latest version of yt-dlp. the video `dqRZDebPIGs` (18.8MB) is downloaded in only two seconds using the tvhtml5 embedded client. But now I see that it is only the 360p version that has a `ratebypass=yes` parameter (is that what you need to avoid throttling?). When i download the 1080p version (68.5MB) then i takes 8 seconds for the 5 minute video.

Responses from clients such as `ANDROID` are not throttled. This means that you can take the response URL as is, and download at normal speed. However `ANDROID` client has age restriction. `TVHTML5_SIMPLY_EMBEDDED_PLAYER` does not have age restriction, but response URLs are throttled. That means if you take the response URL as is, it will be slow download speed.

Projects such as YT-DLP has worked around this by parsing the JavaScript YouTube code, and changing the URL such that it runs at full speed. Ideally I would like to avoid this solution, as its quite painful to parse JavaScript with another language, especially in this situation as the JavaScript has been minified and obfuscated.

The video you gave `dqRZDebPIGs` is not a great example for this discussion, because if you request it with the `TVHTML5_SIMPLY_EMBEDDED_PLAYER` client, then you get a response like this:

~~~
"signatureCipher": "s=8GKIy930KD5sSK1Mpz96Dvan9Colpm1bSISNx4381BFICwiLIbdzMPPnmuJ
DvcunB9_EeHuWnBwIbGLbE194YAgfgIARw8JQ0qOAqOvqOv&sp=sig&url=https://rr1---sn-q4flr
nsl.googlevideo.com/videoplayback%3Fexpire%3D1649476931%26ei%3D47BQYtKwHZS1igT...
~~~

So, even if we had some way to avoid the throttling, youd still have to deal with decrypting the signature, so JavaScript would be unavoidable. These videos are different:

~~~
SZJvDhaSDnc
Tq92D6wQ1mg
~~~

The are blocked by the `ANDROID` client, but they work with the `TVHTML5_SIMPLY_EMBEDDED_PLAYER` client. In addition, they return URL with signature already decrypted:

~~~
"url": "https://rr1---sn-q4flrnle.googlevideo.com/videoplayback?expire=1649477608
&ei=iLNQYuNLhaWKvg-8lp2gBA&ip=72.181.23.38&id=o-AHaleqa6xu149rIm6gxp1TOkpo4lGTqqu
7Ok_QkGkCiS&itag=18&source=youtube&requiressl=yes&mh=bB&mm=31%2C26&mn=sn-q4flr...
~~~

So assuming I could deal with the throttling some way, then no JavaScript needed.

**Comment by zerodytrash** [comment]
i am thinking if it makes sense to create a webservice for this. https://github.com/fent/node-ytdl-core can decipher the googlevideo url. you pass the ciphered url and the signature timestamp to the webservice and it returns the deciphered url.

**Comment by 89z** [comment]
> i am thinking if it makes sense to create a webservice for this. https://github.com/fent/node-ytdl-core can decipher the googlevideo url. you pass the ciphered url and the signature timestamp to the webservice and it returns the deciphered url.

For my project, I have different goals than other projects. Other projects want to avoid login at all cost. I would like to avoid login, but if it means having to parse JavaScript (or use some webservice), then I am OK with login. Also, I implemented OAuth for YouTube [1], so the login process is streamlined, as no cookies are required.

This will mean that my project will require more logins than other projects, but no requirement to parse JavaScript. I think I found a way to avoid throttle without JavaScript, but I need to do more testing.

1. https://github.com/89z/mech/blob/v1.51.3/youtube/exchange.go

**Comment by zerodytrash** [comment]
That's nice! It is more comfortable than exchanging cookies and if the refresh token works as expected then you are permanently authenticated. It's more comfortable than exchanging cookies and with the refresh token you are permanently authenticated. I could use this also for my [Account Proxy](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/tree/main/account-proxy) because sometimes the cookies expire.

**Comment by 89z** [comment]
> That's nice! It is more comfortable than exchanging cookies and if the refresh token works as expected then you are permanently authenticated. I could use this also for my [Account Proxy](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/tree/main/account-proxy) because sometimes the cookies expire.

I think the refresh token is permanent (unless you revoke it). However the access token only last 1-12 hours. This is a feature, as if you accidentally share your access token, it auto expires for your protection.

**Comment by 89z** [comment]
Also, OAuth is better than cookies, as you can scope the token to YouTube specifically, while cookies give access to the entire Google account.

**Comment by zerodytrash** [comment]
> Also, OAuth is better than cookies, as you can scope the token to YouTube specifically, while cookies give access to the entire Google account.

This gives me the idea to offer a public token provider. For age restricted videos, an access token is retrieved from the server which is used client side to unlock the video. This has the advantage that no video id gets sent to the server and the privacy is better. The google account used does not contain private information but the user would have write access to the youtube account. Not sure if this could cause problems.

**Comment by 89z** [comment]
Its an all around better solution I think. The drawback I found is that most sites are shitty about giving you OAuth client details. All you should have to do is give your credentials, and server should return a refresh token, but most sites Ive seen want you to go through this painful "client app" creation process.

I worked around this by just borrowing the "YouTube on TV" app details [1]. However this trouble would only be for the person setting up the token provider, the end users wouldnt have to deal with those details.

1. https://github.com/89z/mech/blob/v1.51.3/youtube/exchange.go#L19-L25

**Comment by zerodytrash** [comment]
The only thing that could happen is that the YouTube channel could be suspended if it is accessed from many different IPs. Google has some protection mechanisms that protect against unauthorized access, but they may not apply to OAuth clients. I will try this because your approach is very interesting.

**Comment by 89z** [comment]
> The only thing that could happen is that the YouTube channel could be suspended if it is accessed from many different IPs. Google has some protection mechanisms that protect against unauthorized access, but they may not apply to OAuth clients.

The OAuth flow makes two requests to get the refresh token. Both requests require a OAuth client ID. Its possible they could revoke the OAuth client, but its unlikely as it would require software update for every single YouTube TV in the United States.

Between the two OAuth requests, the person setting up the token provider logs into their Google account with a special URL and enters a user code. So yes, if Google wanted to, they could nuke the linked Google account. I'm not sure how they monitor that, but I guess you will find out if you try it.

**Comment by 89z** [comment]
It works! So it found out, even if you have a throttled URL, you can just download the file in pieces for extra speed:

~~~
aria2c -s 16 -x 16 -k 1048576 --disable-ipv6 `
'https://rr4---sn-q4flrnss.googlevideo.com/videoplayback?expire=1649489917&ei=neNQYvvMDriZ2_gPmf-D-AM&ip=...'
~~~

Result was about 685 kB/s, or about 16 times faster than the normal slow speed. The above program has max 16 connections, but I could write my own downloader that does more. I'm not sure if Google has a connection limit, I will do more checking. I am kind of surprised no one tried this before (or did they?)

**Comment by zerodytrash** [comment]
that's insane! :D not sure if this is already known. its definitely easier than processing the cipher xd

**Comment by 89z** [comment]
It wont work in all cases, as some responses have `signatureCipher` instead of `url`, but for any `url` responses, you should be able to bypass the throttling without JavaScript. I got distracted working on my Twitter extractor today, but I might have some time to work on the YouTube stuff tomorrow. Also another user mentioned that you can switch the domain and avoid the cipher and/or throttling, but I don't know if any truth to that.

**Comment by 89z** [comment]
Check this out, I got 3.67 MiB per second on a throttled video:

~~~
PS C:\> pget -o o -p 99 'https://rr4---sn-q4flrnss.googlevideo.com/videoplayback?expire=1649656170&ei=Cm1TYor2No20lu8Pgde_6Aw&ip=...
55.23 MiB / 55.23 MiB [------------------------------------] 100.00% 3.67 MiB p/s
~~~

This was using 99 connections. I could go higher, but I think that result is good.

**Comment by zerodytrash** [comment]
maybe youtube just want to adjust the buffering of the player to the video duration in order to transfer less data. YouTube would have to throttle on IP basis to prevent this trick. They wouldn't do that because then you could only stream one video smoothly at the same time from your IP.

**Comment by 89z** [comment]
I don't want to abuse it, but I think the above is a reasonable action. With normal videos, I use a single connection with max speed, which for me is about 8 MB/s. So this is more connections, but less speed overall. I just don't want to have to deal with parsing JavaScript, so this seems like a good option. I'm gonna try to work up a module, as I want something a little more basic than Pget. I guess the original issue is solved here, so we can close this if you want.
